name: Send email new RSS Feed items	
on:
  rss:
    url: https://feedx.fun/rss/zhihudaily.xml
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: 626522796@qq.com
          from: cid5798@gmail.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
